### Implementing Linear Regression

### sklearn.linear_model.Linear_Regression

#### Ordinary least squares Linear Regression.

LinearRegression fits a linear model with coefficients w = (w1, …, wp) to minimize the residual sum of squares between the observed targets in the dataset, and the targets predicted by the linear approximation.

#### Parameters: 

fit_interceptbool, default=True
Whether to calculate the intercept for this model. If set to False, no intercept will be used in calculations (i.e. data is expected to be centered).

normalizebool, default=False
This parameter is ignored when fit_intercept is set to False. If True, the regressors X will be normalized before regression by subtracting the mean and dividing by the l2-norm. If you wish to standardize, please use StandardScaler before calling fit on an estimator with normalize=False.

Deprecated since version 1.0: normalize was deprecated in version 1.0 and will be removed in 1.2.

copy_Xbool, default=True
If True, X will be copied; else, it may be overwritten.

n_jobsint, default=None
The number of jobs to use for the computation. This will only provide speedup in case of sufficiently large problems, that is if firstly n_targets > 1 and secondly X is sparse or if positive is set to True. None means 1 unless in a joblib.parallel_backend context.

positivebool, default=False
When set to True, forces the coefficients to be positive. This option is only supported for dense arrays.


In [4]:
### Implementation of OLS

### importing libraries

import numpy as np
from sklearn.linear_model import LinearRegression

X = np.array([[1,1], [2,3], [3,4], [4, 6]])
y = np.dot(X, np.array([1,2])) + 3
reg = LinearRegression().fit(X,y)
reg.score(X,y)


1.0

In [7]:
reg.coef_

array([1., 2.])

In [8]:
reg.intercept_

2.9999999999999964

In [10]:
reg.predict(np.array([[5,6]]))

array([20.])

In [11]:
reg.get_params(deep = True)

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': False,
 'positive': False}

### Implementing Ridge regression

Linear least squares with l2 regularization

Minimizes the objectives function: ||y - Xw||^2_2 + alpha * ||w||^2_2

Parameters:

alpha{float, ndarray of shape (n_targets,)}, default=1.0
Constant that multiplies the L2 term, controlling regularization strength. alpha must be a non-negative float i.e. in [0, inf).

When alpha = 0, the objective is equivalent to ordinary least squares, solved by the LinearRegression object. For numerical reasons, using alpha = 0 with the Ridge object is not advised. Instead, you should use the LinearRegression object.

fit_interceptbool, default=True Whether to calculate the intercept for this model. If set to False, no intercept will be used in calculations (i.e. data is expected to be centered).

normalizebool, default=False This parameter is ignored when fit_intercept is set to False. If True, the regressors X will be normalized before regression by subtracting the mean and dividing by the l2-norm. If you wish to standardize, please use StandardScaler before calling fit on an estimator with normalize=False.

Deprecated since version 1.0: normalize was deprecated in version 1.0 and will be removed in 1.2.

copy_Xbool, default=True If True, X will be copied; else, it may be overwritten.

n_jobsint, default=None The number of jobs to use for the computation. This will only provide speedup in case of sufficiently large problems, that is if firstly n_targets > 1 and secondly X is sparse or if positive is set to True. None means 1 unless in a joblib.parallel_backend context.

positivebool, default=False When set to True, forces the coefficients to be positive. This option is only supported for dense arrays.



In [18]:
import numpy as np
from sklearn.linear_model import Ridge
ran = np.random.RandomState(0)

number_Of_Samples, number_Of_Features = 10, 5
y = ran.randn(number_Of_Samples)
X = ran.randn(number_Of_Samples, number_Of_Features)

clx = Ridge(alpha = 1.0).fit(X,y)


In [19]:
clx.score(X,y)

0.6836781050289735

In [20]:
Ridge()

Ridge()

In [21]:
clx.get_params()

{'alpha': 1.0,
 'copy_X': True,
 'fit_intercept': True,
 'max_iter': None,
 'normalize': False,
 'random_state': None,
 'solver': 'auto',
 'tol': 0.001}

### Implementing Lasso Regression

Linear Model trained with L1 prior as regularizer (aka the Lasso).

The optimization objective for Lasso is:

(1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1

In [22]:
import numpy as np
from sklearn.linear_model import Lasso

rng = np.random.RandomState(0)
number_Of_Samples, number_of_features = 10, 5

X = rng.randn(number_Of_Samples, number_of_features)
y = rng.randn(number_Of_Samples)

clf = Lasso(alpha = 1.0).fit(X,y)

clf.coef_

array([-0.,  0.,  0., -0.,  0.])

In [23]:
clf.intercept_

-0.2427925882379088

In [24]:
print(clf.coef_)

[-0.  0.  0. -0.  0.]


### Implementing ElasticNet

Linear regression with combined L1 and L2 priors as regularizer.

Minimizes the objective function:

1 / (2 * n_samples) * ||y - Xw||^2_2
+ alpha * l1_ratio * ||w||_1
+ 0.5 * alpha * (1 - l1_ratio) * ||w||^2_2
If you are interested in controlling the L1 and L2 penalty separately, keep in mind that this is equivalent to:

a * ||w||_1 + 0.5 * b * ||w||_2^2
where:

alpha = a + b and l1_ratio = a / (a + b)

In [25]:
import numpy as np
from sklearn.linear_model import ElasticNet
from sklearn.datasets import make_regression

X, y = make_regression(n_features = 2, random_state = 0)

regr = ElasticNet(random_state = 0)

regr.fit(X,y)

ElasticNet(random_state=0)

In [26]:
regr.coef_

array([18.83816048, 64.55968825])

In [27]:
regr.score(X,y)

0.8904453086976037

In [28]:
regr.intercept_

1.4512607561654032

In [29]:
regr.predict(np.array([[1,2]]))

array([149.40879773])